### ISSUE TITLE
[MissingDependencyError]: Should this be a major problem as per conventions

### ISSUE THREAD

**Issue by rdandnayak** [TypeCtrl/ngx-chartjs#162]
You can visit this link to figure out
https://bundlephobia.com/result?p=@ctrl/ngx-chartjs

i was not able to get the impact this will cause for my project.

Also as a new feature, i would prefer to import specific chart types (bar/pie) instead of importing entire chart Module, to save tax on importing unnecessary components

**Comment by scttcper** [comment]
https://bundlephobia.com/result?p=@ctrl/ngx-chartjs@4.0.1

Chartjs doesn't really support that.
