### ISSUE TITLE
Charts are no longer responsive after update to ngx-chartjs^6

### ISSUE THREAD

**Issue by brianroadifer** [TypeCtrl/ngx-chartjs#170]
I am not sure if the error is coming from ngx-chartjs or chart.js itself. I am leaning towards ngx-chartjs since the component looks to have been rewritten for the update. I also looked at this projects website, but the website isn't responsive from what I can tell, so it isn't a good sample for a comparison.

**Comment by scttcper** [comment]
You would need to enable the responsive option in chart options

**Comment by brianroadifer** [comment]
I have the chart option enabled and it still isn't responsive. Here is what my options object looks like.

```typescript
options: ChartOptions = {
        responsive: true,
        aspectRatio: 2,
        scales: {
          y: {
            type: 'linear',
            position: 'left',
            min: 0,
            max: 100,
            ticks: { stepSize: 25 },
          },
        },
        elements: {
          line: {
            tension: 0,
          },
        },
        plugins: {
          tooltip: {
            enabled: true,
            position: 'nearest',
          },
          legend: {
            display: false,
            position: 'top',
          },
        },
      };
```
Package versions
chart.js: 3.1.1
@ctrl/ngx-chartjs: 6.0.0

**Comment by scttcper** [comment]
I'm not sure, that's working for me in the demo app. Here you can see them resizing on smaller screens

https://user-images.githubusercontent.com/1400464/116731965-45bf6f00-a99f-11eb-9645-e04e7869df17.mp4

**Comment by brianroadifer** [comment]
Strange. I am looking at the demo website on Chrome/Edge 90 and Firefox 88 and the charts aren't updating.


https://user-images.githubusercontent.com/12088454/116748449-b628b900-a9bc-11eb-9c11-c47e3ca85975.mp4


https://user-images.githubusercontent.com/12088454/116748453-b6c14f80-a9bc-11eb-83f9-ac4d531157f9.mp4

**Comment by brianroadifer** [comment]
I made a StackBlitz of how I am using it.
https://stackblitz.com/edit/ngx-chartjs-sample

**Comment by scttcper** [comment]
thanks, looks like ngx-chartjs element needs display block

**Comment by scttcper** [comment]
No idea how good of a fix that will be or if i need to put the canvas inside a div instead.

**Comment by brianroadifer** [comment]
I updated the StackBlitz to the latest and that seems to resolve it. Thanks!
