### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by westlakem** [TypeCtrl/ngx-chartjs#62]
When the "responsive" flag is set to true, the graph grows as the screen gets bigger, but it doesn't shrink when the screen gets smaller.  You can see this by shrinking the width of your browser.

**Comment by scttcper** [comment]
I believe they're all responsive on the demo page? Which appears to be working for me. Growing and shrinking in chrome 69

**Comment by JiajiSun** [comment]
> When the "responsive" flag is set to true, the graph grows as the screen gets bigger, but it doesn't shrink when the screen gets smaller. You can see this by shrinking the width of your browser.

same issue here, graph grows as the screen width increased, but doesn't shrink when screen width decreased.

**Comment by scttcper** [comment]
going to need an example and browser information

**Comment by scttcper** [comment]
Also, what responsive flag are you setting?

**Comment by JiajiSun** [comment]
> Also, what responsive flag are you setting?

Fixed the issue by setting parent div with a width instead of using flex-grow

**Comment by westlakem** [comment]
same fix as @JiajiSun 

Set a width as seen in the important note: https://www.chartjs.org/docs/latest/general/responsive.html
