### ISSUE TITLE
Line Chart - stacked area doesn't stack the data

### ISSUE THREAD

**Issue by JiajiSun** [TypeCtrl/ngx-chartjs#63]
I am trying to use the ngx-chartjs for a stacked area chart, but the data is not stacking as expected:
Here are the options setting for my chart: 

options: {
    responsive: true,
    title: {
      display: true,
      text: 'Chart.js Line Chart - Stacked Area'
    },
    tooltips: {
      mode: 'index',
    },
    hover: {
      mode: 'index'
    },
    scales: {
      xAxes: [{
        scaleLabel: {
          display: true,
          labelString: 'Month'
        }
      }],
      yAxes: [{
        stacked: true,
        scaleLabel: {
          display: true,
          labelString: 'Value'
        }
      }]
    }
  };

The scaleLabel are not showing in chart, and the chart is not stacked.
The scales part doesn't seems working correctly.
Could you provide an example for the scales part?

**Comment by scttcper** [comment]
This is a wrapper around [chart.js](https://www.chartjs.org/). Try looking through their examples first. Everything in options is passed to chart.js directly
