### ISSUE TITLE
Updating Options & annotations

### ISSUE THREAD

**Issue by westlakem** [TypeCtrl/ngx-chartjs#66]
I've got an array of annotations:

            this.options.annotation.annotations.push({
              // drawTime: 'beforeDatasetsDraw',
              id: 'vline' + i,
              type: 'line',
              mode: 'vertical',
              scaleID: 'x-axis-0',
              value: event.year,
              borderColor: 'black',
              borderWidth: 3,
              label: {
                backgroundColor: 'black',
                content: event.description,
                enabled: true,
                position: 'top'
              }
            });

And when I want to update the value of that annotation, nothing happens.

I've tried:
1. Reassigning the value directly
```
this.options.annotation.annotations[i].value = event.year;
```
2. Making a brand new `options` object
```
 const copy = JSON.parse(JSON.stringify(this.options));
 copy.annotation.annotations[i].value = event.year;
 this.options = copy;
```
3.  rebuilding the array and setting the array onto annotations
```
this.options.annotation.annotations = myNewArray;
```

I'm not sure what else to try.

**Comment by scttcper** [comment]
https://github.com/chartjs/chartjs-plugin-annotation/issues/88#issuecomment-426603998

try without giving the annotation an ID
