### ISSUE TITLE
Using renderChart(), the previous chart do not get destroyed

### ISSUE THREAD

**Issue by evandrogrm** [TypeCtrl/ngx-chartjs#67]
Hi, thank you for all your work.
I put a combo-box in my dashboard with the types, so the user can select the types they want.
I notice that there is a method called `renderChart()`. When I use it, calling the method:
```
this.chart.type = newType;
this.chart.renderChart();
```
When I hover the mouse in any datasets, the previous chart takes place in front.

Them, I needed to call this instead:
```
this.chart.chartInstance.destroy();
this.chart.type = newType;
this.chart.renderChart();
```
And now, my charts is working just fine.
I am reporting this, because I think it is a little thing, that could mess up in the future.

Them maybe in [these lines](https://github.com/TypeCtrl/ngx-chartjs/blob/99f889ea02ed643343cff4df2997ec1ca6cde198/src/lib/chartjs.component.ts#L146) you could do this:
```
this.zone.runOutsideAngular(() => {
    this.chartInstance.destroy(); // <<<<<
    this.chartInstance = new Chart(node, {
    type: this.type,
    data,
    options: this.options,
    plugins: this.plugins,
    });
});
```

If you want, I can send a PR. Thank you.

**Comment by scttcper** [comment]
Did you try setting `[redraw]="true"`? https://github.com/TypeCtrl/ngx-chartjs/blob/master/src/lib/chartjs.component.ts#L65-L69

**Comment by evandrogrm** [comment]
Yes, without destroying it manually, when I hover it, the previous chart takes place either.

**Comment by scttcper** [comment]
if you are passing chart as an object, this won't trigger ngOnChanges.

```ts
this.chart.type = newType;
```

should be 
```ts
this.chart = { ...this.chart, type: newType };
```

or whatever. make sure whatever you're doing is firing ngOnChanges.

**Comment by evandrogrm** [comment]
This is my select
```
<select class="form-control-sm chart-type" [(ngModel)]="chart.type" [compareWith]="compareWith" (change)="refresh()">
    <option *ngFor="let $t of types" [value]="$t.value">{{ $t.name }}</option>
</select>

types = [
    {
        value: 'bar',
        name: 'Bar'
    },
    {
        value: 'line',
        name: 'Line'
    }
];
```
This method
```
changeType(typeName: string) {
    this.chart = { ...this.chart, type: typeName };
}
```
Is returning

> Type '{ type: string; chartInstance: any; ref: ElementRef<HTMLCanvasElement>; chartClick: EventEmitter<ChartClickEvent>; data: any; height: number; width: number; legend: any; options: any; plugins: any[]; redraw: boolean; datasetKeyProvider: (x: any) => string; }' is not assignable to type 'ChartjsComponent'.

This method is not working
```
private refresh() {
    // this.chart.chartInstance.destroy();
    this.chart.renderChart();
}
```
This is logging anything
```
ngOnChanges() {
    console.log('ngOnChanges');
}
```

I do not belive the  problem is with `OnChanges`

**Comment by keepframe** [comment]
you can try `ng-chartjs` https://github.com/93Alliance/ng-chartjs
