### ISSUE TITLE
Additional properties are not updating

### ISSUE THREAD

**Issue by DariusNorv** [TypeCtrl/ngx-chartjs#74]
Hi.
First of all thanks for a nice plugin!
I faced one problem with dataset update. When I'm not using redraw option graphs won't to update background and so on. Only points are upgradable.

I've checked sources and prepared a PR.
Hope it solve you problems with Objects merging.

https://github.com/TypeCtrl/ngx-chartjs/pull/73

**Comment by scttcper** [comment]
thanks for the pr
